#!/usr/bin/env node
// The durable overrides layer + the profile-derivation engine.
//
// Provenance model: detected facts are always re-derivable from disk and are
// NEVER the durable truth. The only durable, human-authored artifact is the
// overrides file (overrides.local.json). The workspace profile is a DERIVED
// artifact = detected ⊕ overrides, regenerated by init/update.
//
// This makes `update` correct by construction: re-detect, re-apply the same
// overrides, and the only thing that can go wrong is a *stale* override (one
// pointing at a member that no longer exists) — surfaced as a conflict.
//
// `set` is the deterministic structured writer the guided /orchestrate-config
// command calls with fully-resolved args — the human never types these paths.
//
// Verbs:
//   node overrides.mjs apply <detected.json> <overrides.json> [--out <profile.json>]
//   node overrides.mjs set   <overrides.json> <member> <field> <value>
//   node overrides.mjs unset <overrides.json> <member> <field>
//   node overrides.mjs validate <overrides.json>
//   node overrides.mjs show     <overrides.json>
//
// <field> ∈ role | role_reason | gates.<key> | knowledge.<slot>
//            | knowledge.extra.<name> | note
// Fixed slots/roles/gate-keys are allowlisted; only knowledge.extra.<name> is
// free-form. A nullable value can be cleared with the literal "null"/"none".
// Note: `set … note <text>` APPENDS; there is no per-note addressing, so
// `unset … note` clears ALL notes for that member.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  OVERRIDES_SCHEMA, ROLES, GATE_KEYS, KNOWLEDGE_SLOTS,
  validateOverrides, validateWorkspace,
} from "./schema.mjs";

function die(msg, code = 1) { process.stderr.write(msg + "\n"); process.exit(code); }
function readJSON(p) {
  try { return JSON.parse(fs.readFileSync(p, "utf8")); }
  catch (e) { die(`cannot read/parse ${p}: ${e.message}`); }
}
function emit(text, out) {
  if (out) { fs.writeFileSync(out, text); process.stdout.write(`wrote ${out}\n`); }
  else process.stdout.write(text);
}
function outArg(args) { const i = args.indexOf("--out"); return i >= 0 ? args[i + 1] : null; }

function readOverrides(file, { allowMissing = false } = {}) {
  if (!fs.existsSync(file)) {
    if (allowMissing) return { schema: OVERRIDES_SCHEMA, members: {} };
    die(`overrides file not found: ${file}`);
  }
  const ov = readJSON(file);
  const { valid, errors } = validateOverrides(ov);
  if (!valid) die(`invalid overrides file ${file}:\n  ${errors.join("\n  ")}`);
  if (!ov.members) ov.members = {};
  return ov;
}
function writeValidated(file, ov) {
  ov.schema = OVERRIDES_SCHEMA;
  const { valid, errors } = validateOverrides(ov);
  if (!valid) die("refusing to write invalid overrides:\n  " + errors.join("\n  "));
  fs.mkdirSync(path.dirname(path.resolve(file)), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(ov, null, 2) + "\n");
}

// --- field grammar (engine-internal; the guided command resolves to this) ---

function parseField(field) {
  if (field === "role") return { kind: "role" };
  if (field === "role_reason") return { kind: "role_reason" };
  if (field === "note") return { kind: "note" };
  if (field.startsWith("gates.")) {
    const key = field.slice(6);
    if (!GATE_KEYS.includes(key)) die(`unknown gate "${key}" (known: ${GATE_KEYS.join(", ")})`);
    return { kind: "gate", key };
  }
  if (field.startsWith("knowledge.extra.")) {
    const name = field.slice(16);
    if (!name) die("knowledge.extra.<name> requires a name");
    return { kind: "extra", name };
  }
  if (field.startsWith("knowledge.")) {
    const slot = field.slice(10);
    if (!KNOWLEDGE_SLOTS.includes(slot)) die(`unknown knowledge slot "${slot}" (known: ${KNOWLEDGE_SLOTS.join(", ")})`);
    return { kind: "slot", slot };
  }
  die(`unknown field "${field}" (role | role_reason | gates.<key> | knowledge.<slot> | knowledge.extra.<name> | note)`);
}
const nullable = (raw) => (raw === "null" || raw === "none" || raw === "") ? null : raw;

function pruneMember(m) {
  if (m.gates && Object.keys(m.gates).length === 0) delete m.gates;
  if (m.knowledge) {
    if (m.knowledge.extra && Object.keys(m.knowledge.extra).length === 0) delete m.knowledge.extra;
    if (Object.keys(m.knowledge).length === 0) delete m.knowledge;
  }
  if (m.notes && m.notes.length === 0) delete m.notes;
}

// --- verbs ------------------------------------------------------------------

function cmdSet(file, member, field, raw) {
  if (!member || !field || raw === undefined) die("usage: overrides.mjs set <overrides.json> <member> <field> <value>");
  const d = parseField(field);
  const ov = readOverrides(file, { allowMissing: true });
  const m = (ov.members[member] ||= {});
  switch (d.kind) {
    case "role":
      if (!ROLES.includes(raw)) die(`role must be one of ${ROLES.join(", ")}`);
      m.role = raw; break;
    case "role_reason": m.role_reason = raw; break;
    case "gate": (m.gates ||= {})[d.key] = nullable(raw); break;
    case "slot": (m.knowledge ||= {})[d.slot] = nullable(raw); break;
    case "extra": (m.knowledge ||= {}); (m.knowledge.extra ||= {})[d.name] = raw; break;
    case "note": (m.notes ||= []).push(raw); break;
  }
  writeValidated(file, ov);
  process.stdout.write(`set ${member}.${field} = ${JSON.stringify(raw)} (${file})\n`);
}

function cmdUnset(file, member, field) {
  if (!member || !field) die("usage: overrides.mjs unset <overrides.json> <member> <field>");
  const d = parseField(field);
  const ov = readOverrides(file, { allowMissing: true });
  const m = ov.members[member];
  if (!m) die(`no overrides for member "${member}"`);
  switch (d.kind) {
    case "role": delete m.role; break;
    case "role_reason": delete m.role_reason; break;
    case "gate": if (m.gates) delete m.gates[d.key]; break;
    case "slot": if (m.knowledge) delete m.knowledge[d.slot]; break;
    case "extra": if (m.knowledge && m.knowledge.extra) delete m.knowledge.extra[d.name]; break;
    case "note": delete m.notes; break;
  }
  pruneMember(m);
  if (Object.keys(m).length === 0) delete ov.members[member];
  writeValidated(file, ov);
  process.stdout.write(`unset ${member}.${field} (${file})\n`);
}

// detected ⊕ overrides → derived profile (+ stale-override conflicts).
export function applyOverrides(detected, overrides) {
  const profile = JSON.parse(JSON.stringify(detected));
  delete profile.decisions_needed; // derived profile is finalized
  const conflicts = [];
  const byId = new Map(profile.members.map((m) => [m.id, m]));
  for (const [id, mo] of Object.entries((overrides && overrides.members) || {})) {
    const m = byId.get(id);
    if (!m) { conflicts.push({ member: id, reason: "override targets a member no longer present in detection" }); continue; }
    if (mo.role !== undefined) m.role = mo.role;
    if (mo.role_reason !== undefined) m.role_reason = mo.role_reason;
    if (typeof m.role === "string" && m.role.startsWith("chuck-")) delete m.role_reason;
    if (mo.gates) { m.gates = { ...m.gates }; for (const [k, v] of Object.entries(mo.gates)) m.gates[k] = v; }
    if (mo.knowledge) {
      m.knowledge = m.knowledge || { claude_md: null, skills: null, rubrics: null, extra: {} };
      for (const slot of KNOWLEDGE_SLOTS) if (mo.knowledge[slot] !== undefined) m.knowledge[slot] = mo.knowledge[slot];
      if (mo.knowledge.extra) m.knowledge.extra = { ...(m.knowledge.extra || {}), ...mo.knowledge.extra };
    }
    if (mo.notes) m.notes = [...(m.notes || []), ...mo.notes];
  }
  return { profile, conflicts };
}

function cmdApply(detectedFile, overridesFile, out) {
  if (!detectedFile || !overridesFile) die("usage: overrides.mjs apply <detected.json> <overrides.json> [--out <path>]");
  const detected = readJSON(detectedFile);
  const overrides = readOverrides(overridesFile, { allowMissing: true });
  const { profile, conflicts } = applyOverrides(detected, overrides);
  const { valid, errors } = validateWorkspace(profile);
  if (!valid) die("derived profile is INVALID:\n  " + errors.join("\n  "));
  for (const c of conflicts) process.stderr.write(`CONFLICT: ${c.member}: ${c.reason}\n`);
  emit(JSON.stringify(profile, null, 2) + "\n", out);
}

function cmdValidate(file) {
  const { valid, errors } = validateOverrides(readJSON(file));
  if (!valid) die("INVALID:\n  " + errors.join("\n  "));
  process.stdout.write("OK\n");
}

function cmdShow(file) {
  const ov = readOverrides(file, { allowMissing: true });
  const ids = Object.keys(ov.members);
  if (ids.length === 0) { process.stdout.write("(no overrides)\n"); return; }
  for (const id of ids) {
    process.stdout.write(`- ${id}:\n`);
    const m = ov.members[id];
    if (m.role !== undefined) process.stdout.write(`    role: ${m.role}${m.role_reason ? ` (${m.role_reason})` : ""}\n`);
    if (m.gates) for (const [k, v] of Object.entries(m.gates)) process.stdout.write(`    gates.${k}: ${v}\n`);
    if (m.knowledge) {
      for (const slot of KNOWLEDGE_SLOTS) if (m.knowledge[slot] !== undefined) process.stdout.write(`    knowledge.${slot}: ${m.knowledge[slot]}\n`);
      if (m.knowledge.extra) for (const [n, v] of Object.entries(m.knowledge.extra)) process.stdout.write(`    knowledge.extra.${n}: ${v}\n`);
    }
    if (m.notes) for (const n of m.notes) process.stdout.write(`    note: ${n}\n`);
  }
}

// --- CLI --------------------------------------------------------------------

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const [verb, ...rest] = process.argv.slice(2);
  const out = outArg(rest);
  switch (verb) {
    case "apply": cmdApply(rest[0], rest[1], out); break;
    case "set": cmdSet(rest[0], rest[1], rest[2], rest[3]); break;
    case "unset": cmdUnset(rest[0], rest[1], rest[2]); break;
    case "validate": if (!rest[0]) die("usage: overrides.mjs validate <overrides.json>"); cmdValidate(rest[0]); break;
    case "show": if (!rest[0]) die("usage: overrides.mjs show <overrides.json>"); cmdShow(rest[0]); break;
    default: die("usage: overrides.mjs <apply|set|unset|validate|show> ...");
  }
}

export { parseField };
